spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB_NAME:task_service_db}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog-master.yml

  application:
    name: task-service

jwt:
  secret:
    key: ${JWT_SECRET_KEY:key}
  expired:
    access-time: ${JWT_EXPIRED_ACCESS_TIME:3600000}
    refresh-time: ${JWT_EXPIRED_REFRESH_TIME:15724800000}

cron:
  refresh-token:
    clear: 0 0 0 * * ?
